Handle nonexistant analyzers
Trying to submit to an analyzer that is not configured results in an
AttributeError because property id of the analyzer object is accessed
regardless of the result of get_by_name:

  File "/cortex4py/cortex4py/controllers/analyzers.py", line 90, in run_by_name
    return self.run_by_id(analyzer.id, observable, **kwargs)
AttributeError: 'NoneType' object has no attribute 'id'

Add a check for the result of get_by_name() and throw a CortexError with
explanatory message on failure.

Signed-off-by: Michael Weiser <michael.weiser@gmx.de>